apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-pvc 
  namespace: thanu-ns1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: nfs-sc    